import React from 'react';

interface GhostFormFieldProps {
  id: string;
  label: string;
  value: string;
  ghostValue?: string;
  placeholder: string;
  isTextarea?: boolean;
  onChange: (value: string) => void;
  onFocus?: () => void;
  onBlur?: () => void;
  onHover?: (hovering: boolean) => void;
  onAcceptGhost?: (fieldId: string) => void;
  onFieldSearch?: (fieldId: string, value: string) => void;
  hasAISuggestion?: boolean;
  sourceInfo?: {
    page: number;
    snippet: string;
  };
  isAIApproved?: boolean;
}

export function GhostFormField({
  id,
  label,
  value,
  ghostValue,
  placeholder,
  isTextarea = false,
  onChange,
  onFocus,
  onBlur,
  onHover,
  onAcceptGhost,
  onFieldSearch,
  hasAISuggestion = false,
  sourceInfo,
  isAIApproved = false,
}: GhostFormFieldProps) {
  // Always show ghost value when it exists (even if field has text)
  // This allows preview to show even when fields have existing content
  const displayValue = ghostValue || value || '';
  const isGhosted = !!ghostValue;
  const hasAIValue = !!value && (ghostValue || isAIApproved);

  // Simplified - no hover tooltips or accept buttons needed
  // Ghost text is shown automatically when hovering over snippets

  const handleChange = (newValue: string) => {
    onChange(newValue);
    // Trigger reverse search when typing (even if less than 2 chars, to handle clearing fields)
    // This ensures we show all snippets when fields are cleared
    onFieldSearch?.(id, newValue);
  };

  const handleFocus = () => {
    onFocus?.();
    // When field is focused, trigger search to show all snippets if no fields have values
    // This ensures snippets are visible when user clicks on an empty field
    if (!value && !ghostValue) {
      onFieldSearch?.(id, '');
    }
  };

  // Determine styling based on AI state
  const getFieldStyling = () => {
    if (isGhosted) {
      // AI suggested (ghost value) - light blue background
      return 'border-blue-300 bg-blue-50 text-blue-900';
    } else if (hasAIValue && isAIApproved) {
      // AI approved - green outline
      return 'border-green-400 bg-white border-2';
    } else if (hasAIValue) {
      // AI populated but not yet approved - light blue background
      return 'border-blue-300 bg-blue-50';
    }
    return 'border-gray-300 bg-white';
  };

  return (
    <div className="relative">
      <label className="block text-sm text-gray-700 mb-2 flex items-center gap-2">
        {label} <span className="text-red-500">*</span>
        {isGhosted && (
          <span className="text-xs text-blue-600 flex items-center gap-1" title="This field was generated by AI">
            <span className="w-2 h-2 bg-blue-500 rounded-full"></span>
            AI Suggested
          </span>
        )}
        {hasAIValue && isAIApproved && !isGhosted && (
          <span className="text-xs text-green-600 flex items-center gap-1" title="This field was generated by AI and approved">
            <span className="w-2 h-2 bg-green-500 rounded-full"></span>
            AI Approved
          </span>
        )}
        {hasAIValue && !isAIApproved && !isGhosted && (
          <span className="text-xs text-blue-600 flex items-center gap-1" title="This field was generated by AI">
            <span className="w-2 h-2 bg-blue-500 rounded-full"></span>
            AI Generated
          </span>
        )}
      </label>
      
      <div className="relative">
        {isTextarea ? (
          <textarea
            id={id}
            placeholder={placeholder}
            value={displayValue}
            onChange={(e) => handleChange(e.target.value)}
            onFocus={handleFocus}
            onBlur={onBlur}
            rows={3}
            className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none transition-all ${getFieldStyling()} ${
              isGhosted ? 'italic' : ''
            }`}
            title={isGhosted ? "This field was generated by AI" : hasAIValue ? "This field was generated by AI" : undefined}
          />
        ) : (
          <input
            id={id}
            type="text"
            placeholder={placeholder}
            value={displayValue}
            onChange={(e) => handleChange(e.target.value)}
            onFocus={handleFocus}
            onBlur={onBlur}
            className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all ${getFieldStyling()} ${
              isGhosted ? 'italic' : ''
            }`}
            title={isGhosted ? "This field was generated by AI" : hasAIValue ? "This field was generated by AI" : undefined}
          />
        )}
      </div>
    </div>
  );
}